typedef enum tagMPSCAN_TYPE {
	MPSCAN_TYPE_UNKNOWN = 0,
	MPSCAN_TYPE_QUICK = 1,
	MPSCAN_TYPE_FULL = 2,
	MPSCAN_TYPE_RESOURCE = 3,
	MPSCAN_TYPE_MAXVALUE = 3
} MPSCAN_TYPE, * PMPSCAN_TYPE;

#define MP_MIDL_STRING 

enum MP_RESOURCE_CLASS
{
	MP_RESOURCE_CLASS_UNKNOWN = 0x0000,
	MP_RESOURCE_CLASS_CONCRETE = 0x0001,
	MP_RESOURCE_CLASS_LATENT = 0x0002,
	MP_RESOURCE_CLASS_SAMPLE_FILE = 0x0004,
	MP_RESOURCE_CLASS_SHARED = 0x0100
};

typedef struct tagMPRESOURCE_INFO {
	MP_MIDL_STRING LPWSTR Scheme;
	MP_MIDL_STRING LPWSTR Path;
	MP_RESOURCE_CLASS Class;
} MPRESOURCE_INFO, * PMPRESOURCE_INFO;

typedef struct tagMPSCAN_RESOURCES {
	DWORD            dwResourceCount;
	PMPRESOURCE_INFO pResourceList;
} MPSCAN_RESOURCES, * PMPSCAN_RESOURCES;